---
# https://access.redhat.com/products/identity-management#getstarted
# https://www.howtoforge.com/tutorial/install-and-configure-freeipa-server-on-centos-8/

- name: Set up FreeIPA
  block:

    - name: Ensure hostname doesn't resolve to localhost
      replace:
        path: /etc/hosts
        regexp: '^127.0.0.1\t{{ FQDN }}\t{{ HOSTNAME }}'
        replace: '{{ IP_ADDRESS }}\t{{ FQDN }}\t{{ HOSTNAME }}'

    - name: Enable FreeIPA package
      command: dnf module -y enable idm:DL1

    - name: Install FreeIPA server
      command: dnf install -y ipa-server
      # package:
      #   name: ipa-server

    - name: Configure FreeIPA server
      command: ipa-server-install --unattended --admin-password={{ ADMIN_PASSWORD }} --ds-password={{ ADMIN_PASSWORD }} --hostname={{ FQDN }} --domain={{ DOMAIN }} --realm={{ DOMAIN|upper }}
      args:
        creates: /var/log/ipaserver-install.log

    - name: Ensure admin config / auth to Kerberos realm
      shell: echo '{{ ADMIN_PASSWORD }}' | kinit admin

    - name: Disable redirects to hard-coded domain
      replace:
        path: /etc/httpd/conf.d/ipa-rewrite.conf
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      with_items:
        - { regexp: '^(RewriteRule \^/\$) (https://.*)(/ipa/ui.*)$', replace: '\1 \3' }
        - { regexp: '^(RewriteRule \^\/ipa\/\(.*)$', replace: '#\1' }
        - { regexp: '^(RewriteCond .*)$', replace: '#\1' }

    - name: Deactivate HTTP RefererError
      replace:
        path: '/usr/lib/python2.7/site-packages/ipaserver/rpcserver.py'
        regexp: '{{ item }}'
        replace: '\1pass  # \2'
      with_items:
        - "^([ ]*)(return self.marshal\\(result, RefererError\\(referer)"

    - name: Activate webserver configuration changes
      service:
        name: httpd
        state: reloaded

  become: true

- name: Create a couple of demo accounts (FreeIPA)
  ipa_user:
    uid: '{{ item.name }}'
    displayname: '{{ item.givenname }} {{ item.surname }}'
    givenname: '{{ item.givenname }}'
    sn: '{{ item.surname }}'
    password: '{{ item.password }}'
    ipa_host: '{{ FQDN }}'
    ipa_pass: '{{ ADMIN_PASSWORD }}'
    validate_certs: no
  with_items:
    - { name: 'jane.doe', givenname: 'Jane', surname: 'Doe', password: 'changeme' }
    - { name: 'john.doe', givenname: 'John', surname: 'Doe', password: 'changeme' }
